#include <inttypes.h>
#include <math.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdio.h>
#if defined(__x86_64__)
#include <x86intrin.h>
#endif

#define DELTA 2e-4

static const uint64_t RUNS = 1524288;

uint64_t time_trig(float (*func)(float), const float x,
		   const uint64_t num_runs) {
	/* Warm the function up */
	for (int i = 0; i < 1000; ++i) {
		func(x);
	}

	uint64_t tic = __rdtsc();
	for (uint64_t i = 0; i < num_runs; ++i) {

		func(x);
	}
	uint64_t toc = __rdtsc();

	return (toc - tic);
}

bool float_within(float f1, float f2, float delta) {
	return fabs(f1 - f2) <= delta;
}

float sin5(float x) {
	/*
	 *Minimax polynomial approximation on [-0.785398, 0.785398].
	 *Degree: 5
	 *Max absolute error: 0.00000005418474415
	 *Generated by remez_polyfit.m in GNU Octave
	 */
	float coeffs[3] = {0.00817107f, -0.16663994f, 0.99999915f};
	float y		= coeffs[0];
	y		= y * x * x + coeffs[1];
	y		= y * x * x + coeffs[2];
	return y * x;
}

float sin3(float x) {
	/*
	 *Minimax polynomial approximation on [-0.785398, 0.785398].
	 *Degree: 3
	 *Max	absolute error: 0.00011567264908152
	 *Generated by remez_polyfit.m in GNU Octave
	 */
	float coeffs[2] = {-0.16051928f, 0.99918540f};
	float y		= coeffs[0];
	y		= y * x * x + coeffs[1];
	return y * x;
}

int main() {
	for (float x = 0; x < M_PI / 40.f; x += 0.00000001) {
		if (!float_within(sin(x), sin3(x), DELTA)) {
			printf("Failed at %f\n", x);
			printf("sin: %f, fake_sin: %f\n", sin(x), sin3(x));
		}
	}
	const float bench = M_PI / 8.0f;
	/* for (float x = 0; x < M_PI / 2.0f; x += 0.001) { */
	/* 	if (!float_within(cos(x), fake_cos(x), DELTA)) { */
	/* 		printf("Failed at %f\n", x); */
	/* 		printf("cos: %f, fake_cos: %f\n", cos(x), fake_cos(x));
	 */
	/* 	} */
	/* } */
	uint64_t real_trig_time = time_trig(sinf, bench, RUNS);
	uint64_t fake_trig_time = time_trig(fake_sin, bench, RUNS);
	printf("Over %" PRIu64 " runs:\nReal sin takes ~%" PRIu64
	       " nanoseconds\nFake sin takes ~%" PRIu64 " nanoseconds\n",
	       RUNS, real_trig_time, fake_trig_time);
	printf("Fake sin takes %f times as long\n",
	       (double)fake_trig_time / (double)real_trig_time);

	return 0;
}
